### ISSUE TITLE
URL ending w/ 'login.jsp' isn't excluded

### ISSUE THREAD

**Issue by bartonhammond** [NeuraLegion/cypress-har-generator#169]
**First off - thanks for this HAR generator - it works great - really **appreciated**!**

**Description**
The HAR still has this `"url": "https://dev/web/login.jsp",` and the userid/password
I don't understand how to set the `excludePaths` to ignore the `url` that ends with `login.jsp`
```
 cy.saveHar({ 
    fileName: fileName,
    content: false,
    excludePaths: ['login\.jsp$', 'logout.jsp$'] 
   });
```
**Steps to reproduce**
Run w/ site that has login.jsp

**Expected behavior**
Exclude `login page` because the `userid/password` is captured

**Actual behavior**
The `login.jsp` page is captured 

**Screenshots**

**Comment by bartonhammond** [comment]
btw, this is a single page application

**Comment by derevnjuk** [comment]
@bartonhammond thanks for the report 👍🏾 

I have added more tests to cover gaps (see #170), however, I was unable to replicate the reported bug.

> I don't understand how to set the excludePaths to ignore the url that ends with login.jsp

Both `login\\.jsp$` and `login.jsp$` are valid options due to the special meaning of the `.` character in regexp (seems we should update an interface to accept the union type `RegExp | string` for clarity). Therefore, there should be no issues with their use. Could you provide additional details, such as the concrete entry that needs to be excluded from the HAR file?

**Comment by bartonhammond** [comment]
Doh!

Thanks - I  decided to just read the json back in and remove what I needed to - i guess a data scrubber.

**Comment by derevnjuk** [comment]
@bartonhammond I will open a separate issue to add support for either the data scrubber or transform functionality.
