### ISSUE TITLE
Support passing electron remote debug flag via cypress browser launch API

### ISSUE THREAD

**Issue by afsmith92** [NeuraLegion/cypress-har-generator#293]
**Description**
As documented in the [readme](https://github.com/NeuraLegion/cypress-har-generator#generating-a-har-file), using this plugin with Electron requires passing CLI arguments

`$ ELECTRON_EXTRA_LAUNCH_ARGS=--remote-debugging-port=9222 cypress run --browser electron`

Is there a reason or limitation why this flag couldn't optionally be passed in via the [cypress browser launch API](https://docs.cypress.io/api/plugins/browser-launch-api#Usage) instead?

```javascript
setupNodeEvents(on, config) {
  on('before:browser:launch', (browser = {}, launchOptions) => {
    if (browser.family === 'electron') {
      launchOptions.args.push('--remote-debugging-port=9222');
    }

    return launchOptions;
  })
}
```

Unfortunately in the environment where I'm running my tests, I'm not able to pass the CLI flag, and ideally I'd be able to use the cypress browser launch API.

**Possible solution**
Currently the plugin [checks if the CLI argument is present](https://github.com/NeuraLegion/cypress-har-generator/blob/88b0c94fab50a90c86c6b82f4f1fc49025260809/src/Plugin.ts#L144) -- this check would need to be relaxed.

**Comment by derevnjuk** [comment]
@afsmith92 thanks for contributing. Unfortunately, Cypress currently has limitations that prevent this feature from being implemented. Cypress ignores the switcher passed via launch options. This means that even if you try to modify the `launchOptions.args` array to include `--remote-debugging-port=9222`, Cypress will not recognize it. According to the Cypress documentation, you have to use the env variable: https://docs.cypress.io/api/plugins/browser-launch-api#Modify-Electron-app-switches

Additionally, there is a bug in Cypress starting from v12.12.0 that prevents overriding the port. This bug is described in issue #288, it also restricts the ability to modify the port for Electron.

So, you may need to consider alternative approaches or workarounds in your testing environment to achieve your desired outcome.

**Comment by afsmith92** [comment]
Thanks for the explanation! I'll close this.
