### ISSUE TITLE
saveHar might cause of failure the tests

### ISSUE THREAD

**Issue by derevnjuk** [NeuraLegion/cypress-har-generator#39]
> If savehar file generator task fails due to network issue in after method, it fails the test as well, is there a way to pass the test case and handle failure this failure.

_Reported by @GayathirideviVenkateswaran on d3d5c92_

**Comment by derevnjuk** [comment]
@GayathirideviVenkateswaran please provide a repository or steps to reproduce, since I'm not sure this issue is related to `cypress-har-generator`.

**Comment by GayathirideviVenkateswaran** [comment]
Hi @derevnjuk , I have after method to save the har file generation. The test completed successfully and during har file generation faced some network issue and har file generation failed stating `cy.task('saveHar')` timed out after waiting `120000ms`.  https://on.cypress.io/task  Because this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `Test case name`. Is it possible to mark the testcase as passed since the entire test case ran successfully or do retry of har file generation ?

**Comment by GayathirideviVenkateswaran** [comment]
This is how I call the function after(() => {cy.saveHar(); });
When we face network error finally after all the test steps completed fully it makes test also failure when failed on savehar file task generation 
<img width="213" alt="Screenshot 2020-06-04 at 6 07 08 PM" src="https://user-images.githubusercontent.com/31467419/83757617-621f3280-a68e-11ea-86e1-952d965f9e6f.png">

<img width="437" alt="Screenshot 2020-06-04 at 6 07 27 PM" src="https://user-images.githubusercontent.com/31467419/83757593-57649d80-a68e-11ea-985e-7d696b281581.png">

**Comment by derevnjuk** [comment]
I have no ideas about the root cause and reproducing steps, closing until reappearing
